# -*- coding: utf-8 -*-
"""RandomForestRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/159mM3HDcsZlfEklb6ZJVzZvB4eeFd2HR

#Random Forest Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""#Training Decision Tree Regression model on the whole dataset"""

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state=0) #Ntree
regressor.fit(X,y)

"""#Predicting a new result"""

regressor.predict([[6.5]])

"""#Visualising the Decision Tree Regression results (higher resolution)"""

x_grid = np.arange(min(X),max(X), 0.1)
x_grid = x_grid.reshape((len(x_grid),1))
plt.scatter(X,y,color='g')
plt.plot(x_grid, regressor.predict(x_grid))
plt.title('Truth or Bluff(SVR)')
plt.xlabel('Position Label')
plt.ylabel('Salary')
plt.show()