# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ebG-gaiB9UqEDsXX7GiB5S0qSHVsa3jm

##Linear Regression
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(X)

print(y)

"""##Training the Simple Linear Regression model on the Training Set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

"""##Predicting the text set Results"""

y_pred = regressor.predict(X_test)

"""##Visualizing the Training set **Results**"""

plt.scatter(X_train,y_train)
plt.plot(X_train, regressor.predict(X_train), color='red')
plt.xlabel('Years of experience')
plt.ylabel('Salary')
plt.title('salary vs Experiences (Training set)')
plt.show()

"""##Visualizing the test set results """

plt.scatter(X_test,y_test)
plt.plot(X_train, regressor.predict(X_train), color='red')
plt.xlabel('Years of experience')
plt.ylabel('Salary')
plt.title('salary vs Experiences (Test set)')
plt.show()

"""##Making a single prediction"""

print(regressor.predict([[60]]))

"""##getting the final linear regression equation with th e value of the coefficients"""

print(regressor.coef_)
print(regressor.intercept_)

